import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import test from 'node:test';
import { verifyPostAuditCorrections } from '../../scripts/ops/r24/corrective/post-audit-corrections.mjs';
import { EXPECTED, verifyToolchain } from '../../scripts/ops/r24/corrective/post-audit-toolchain.mjs';
import { REQUIRED_DEPENDENCIES, verifyDependencyResults, verifyRuleset, verifyRulesetObserverWithAuthority, verifyWorkflowText } from '../../scripts/ops/r24/corrective/post-audit-merge-gate.mjs';

const CLOSURE_VERIFIER='scripts/ops/r24/corrective/stage-admission-verifier-anchor-v2.mjs';
const CLOSURE_VERIFIER_DIGEST='b9cb1d3ad98bbdd0e56dedc4563796f40d9768f1345b57324625ef8386c5bd3f';
const CLOSURE_AUTHORITY='docs/OPS/R24/CORRECTIVE/POST_AUDIT_CORRECTIONS_OWNER_AMENDMENT_V15.json';
const CLOSURE_INSTANCE='docs/OPS/R24/CORRECTIVE/POST_AUDIT_CORRECTIONS_STAGE_INSTANCE_V16.json';
const CLOSURE_ADMISSION='docs/OPS/R24/CORRECTIVE/POST_AUDIT_CORRECTIONS_STAGE_ADMISSION_ATTESTATION_V16.json';
const CLOSURE_AUTHORITY_DIGEST='f39cbf41d3cad609e2ddd852346b8d34cdf6b0dd79ceaa2629e5fdea5b5327ad';
const FINAL_LEASE='docs/OPS/R24/CORRECTIVE/POST_AUDIT_CORRECTIONS_LEASE_RELEASE_V1.json';
const FINAL_MATRIX='docs/OPS/R24/CORRECTIVE/POST_AUDIT_CORRECTIONS_FINAL_ACCEPTANCE_MATRIX_V1.json';
const FINAL_STATE='docs/OPS/R24/CORRECTIVE/POST_AUDIT_CORRECTIONS_FINAL_EFFECTIVE_STATE_V1.json';
const FINAL_REGISTRY='docs/OPS/R24/CORRECTIVE/POST_AUDIT_CORRECTIONS_FINAL_STAGE_REGISTRY_V1.json';
const FINAL_RECEIPT='docs/OPS/R24/CORRECTIVE/POST_AUDIT_CORRECTIONS_FINAL_TERMINAL_RECEIPT_V1.json';
const CYCLE2_AUTHORITY='docs/OPS/R24/CORRECTIVE/POST_AUDIT_CORRECTIONS_OWNER_AMENDMENT_V17.json';
const CYCLE2_INSTANCE='docs/OPS/R24/CORRECTIVE/POST_AUDIT_CORRECTIONS_STAGE_INSTANCE_V18.json';
const CYCLE2_ADMISSION='docs/OPS/R24/CORRECTIVE/POST_AUDIT_CORRECTIONS_STAGE_ADMISSION_ATTESTATION_V18.json';
const sha256=(bytes)=>crypto.createHash('sha256').update(bytes).digest('hex');
const readJson=(file)=>JSON.parse(fs.readFileSync(file));
const gitObjectBytes=(revision,file)=>{const result=spawnSync('git',['show',`${revision}:${file}`],{maxBuffer:64*1024*1024});assert.equal(result.status,0,result.stderr?.toString());return result.stdout;};
function rulesetEnvelope({currentUserCanBypass}={}){return{_links:{html:{href:'https://github.com/KirPonomarev/writer-editor/rules/12270444'},self:{href:'https://api.github.com/repos/KirPonomarev/writer-editor/rulesets/12270444'}},bypass_actors:[],conditions:{ref_name:{exclude:[],include:['~DEFAULT_BRANCH']}},created_at:'2026-01-29T21:32:32.106+02:00',...(currentUserCanBypass===undefined?{}:{current_user_can_bypass:currentUserCanBypass}),enforcement:'active',id:12270444,name:'protect-main',node_id:'RRS_lACqUmVwb3NpdG9yec5DfP9IzgC7O2w',rules:[{type:'deletion'},{type:'non_fast_forward'},{type:'pull_request',parameters:{allowed_merge_methods:['merge','squash','rebase'],dismiss_stale_reviews_on_push:true,require_code_owner_review:false,require_extra_approval_for_unattributed_changes:true,require_last_push_approval:false,required_approving_review_count:0,required_review_thread_resolution:true,required_reviewers:[]}},{type:'required_status_checks',parameters:{do_not_enforce_on_create:false,required_status_checks:[{context:'merge-gate',integration_id:15368}],strict_required_status_checks_policy:false}}],source:'KirPonomarev/writer-editor',source_type:'Repository',target:'branch',updated_at:'2026-08-31T04:53:57.083+03:00'};}
function verifyFinalTransition({lease=readJson(FINAL_LEASE),matrix=readJson(FINAL_MATRIX),state=readJson(FINAL_STATE),registry=readJson(FINAL_REGISTRY),receipt=readJson(FINAL_RECEIPT)}={}){
  assert.deepEqual(lease.lease,{fencingCounter:56,transition:'ACTIVE_WIP_1_TO_RELEASED_WIP_0',status:'RELEASED',wip:0,predecessorReleaseDigest:'583e4209f200cb4dc342f8d05f59b808243e960669d8a0d225586b0e7ff4dd6f',releasedAdmissionDigest:'175953e378ef72d319ea9324bcf6e5ebebfe1c33f59042979d289bb6a9732d39',disposition:'RELEASED_AFTER_DURABLE_CARRIER_PROTECTED_MERGE_AND_FRESH_CLOSURE_SUCCESSOR_PROTECTED_MERGE_EXACT_POSTMERGE_CI'});
  assert.equal(lease.closureSuccessorEvidence.candidateCiStatus,'SUCCESS');
  assert.equal(lease.closureSuccessorEvidence.exactPostmergeCiStatus,'SUCCESS');
  assert.equal(lease.liveWorkObservation.status,'NO_LIVE_WORK');
  assert.equal(matrix.evaluationStatus,'CERTIFIED_DONE');
  assert.equal(matrix.rows.length,matrix.rowCount);
  assert.equal(matrix.rows.every((row)=>row.status==='PASS'),true);
  assert.equal(matrix.passedRowCount,matrix.rowCount);
  assert.equal(matrix.zeroPendingRows,true);
  assert.equal(matrix.bindings.leaseReleaseDigest,sha256(fs.readFileSync(FINAL_LEASE)));
  assert.equal(state.status,'CERTIFIED_DONE');
  assert.deepEqual(state.lease,{fencingCounter:56,status:'RELEASED',wip:0,releaseDigest:sha256(fs.readFileSync(FINAL_LEASE))});
  assert.equal(state.finalAcceptanceMatrixDigest,sha256(fs.readFileSync(FINAL_MATRIX)));
  assert.equal(registry.stages.length,1);
  assert.equal(registry.stages[0].status,'CERTIFIED_DONE_RELEASED');
  assert.equal(registry.stages[0].wip,0);
  assert.equal(registry.stages[0].finalEffectiveStateDigest,sha256(fs.readFileSync(FINAL_STATE)));
  assert.equal(receipt.schemaVersion,'POST_AUDIT_CORRECTIONS_TERMINAL_RECEIPT_V1');
  assert.equal(receipt.status,'CERTIFIED_DONE');
  assert.equal(receipt.evaluationSha,'af0bfb704c13b0195c12b0144415f2e769f99752');
  assert.equal(receipt.evaluationTreeSha,'d3e2232ec01af860794de90f81f2e185cdc3fcfe');
  assert.equal(receipt.finalCarriers.leaseReleaseDigest,sha256(fs.readFileSync(FINAL_LEASE)));
  assert.equal(receipt.finalCarriers.acceptanceMatrixDigest,sha256(fs.readFileSync(FINAL_MATRIX)));
  assert.equal(receipt.finalCarriers.effectiveStateDigest,sha256(fs.readFileSync(FINAL_STATE)));
  assert.equal(receipt.finalCarriers.stageRegistryDigest,sha256(fs.readFileSync(FINAL_REGISTRY)));
  assert.deepEqual(receipt.acceptance,{rowCount:18,passedRowCount:18,pendingRowCount:0,status:'PASS'});
  assert.deepEqual(receipt.effectiveState,{status:'CERTIFIED_DONE',leaseStatus:'RELEASED',fencingCounter:56,wip:0});
  assert.equal(receipt.worktreeProof.protectedUnrelatedBeforeEntriesSha256,receipt.worktreeProof.protectedUnrelatedAfterEntriesSha256);
  assert.equal(receipt.worktreeProof.protectedUnrelatedWipUntouched,true);
  assert.equal(receipt.liveWork.status,'NONE');
  for(const value of [lease,matrix,state,registry,receipt]){assert.equal(value.programDone,false);assert.equal(value.mainProductGraphNodeStarted,false);}
  return {status:'PASS',receiptDigest:sha256(fs.readFileSync(FINAL_RECEIPT))};
}
function closureBaseFixture(){
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'post-audit-terminal-closure-base-'));
  const instance=JSON.parse(fs.readFileSync(CLOSURE_INSTANCE));
  const existing=[...instance.operations.readPaths,...instance.operations.modifyPaths,...instance.operations.deletePaths,...instance.fixedBindings.map(x=>x.path)];
  for(const relative of new Set(existing)){const target=path.join(root,relative);fs.mkdirSync(path.dirname(target),{recursive:true});fs.copyFileSync(relative,target);}
  for(const relative of instance.operations.createPaths)fs.mkdirSync(path.dirname(path.join(root,relative)),{recursive:true});
  return root;
}
function verifyClosureAdmission({instance=CLOSURE_INSTANCE,admission=CLOSURE_ADMISSION}={}){
  return spawnSync(process.execPath,[CLOSURE_VERIFIER,'--repo-root',closureBaseFixture(),'--authority',CLOSURE_AUTHORITY,'--stage-instance',instance,'--stage-admission',admission,'--expected-verifier-digest',CLOSURE_VERIFIER_DIGEST,'--expected-authority-digest',CLOSURE_AUTHORITY_DIGEST],{encoding:'utf8'});
}
function cycle2BaseFixture(){
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'post-audit-cycle2-admission-base-'));
  const instance=readJson(CYCLE2_INSTANCE);
  const existing=[...instance.operations.readPaths,...instance.operations.modifyPaths,...instance.operations.deletePaths,...instance.fixedBindings.map(x=>x.path)];
  for(const relative of new Set(existing)){const target=path.join(root,relative);fs.mkdirSync(path.dirname(target),{recursive:true});fs.copyFileSync(relative,target);}
  for(const relative of instance.operations.createPaths)fs.mkdirSync(path.dirname(path.join(root,relative)),{recursive:true});
  return root;
}
function verifyCycle2Admission(){const authorityDigest=sha256(fs.readFileSync(CYCLE2_AUTHORITY));return spawnSync(process.execPath,[CLOSURE_VERIFIER,'--repo-root',cycle2BaseFixture(),'--authority',CYCLE2_AUTHORITY,'--stage-instance',CYCLE2_INSTANCE,'--stage-admission',CYCLE2_ADMISSION,'--expected-verifier-digest',CLOSURE_VERIFIER_DIGEST,'--expected-authority-digest',authorityDigest],{encoding:'utf8'});}

test('literal normative R24 program preserves fixed identities and 33-stage denominator',()=>{const p=JSON.parse(fs.readFileSync('docs/OPS/R24/CORRECTIVE/R24_CORRECTIVE_PROGRAM_V1_1.json'));assert.equal(p.schemaVersion,'R24_CORRECTIVE_PROGRAM_V1_1');assert.equal(p.stageRegistry.stageOrder.length,33);assert.equal(p.fixedBindings.programTemplateDigest,'6c833c964318da3e61e1743365f8763206be838647b5222c187b3bda8d1c6b9a');assert.equal(p.fixedBindings.stageRegistryDigest,'c8af046b5918f43a50af66886b0b5c9d2e22ea6501240d4b239101d8836ced1a');assert.equal(p.fixedBindings.trustModelDigest,'4f6e4b3a191e0302ea44646659e8c2f71121af7d808cc0ee768269b4e156840d');assert.equal(p.ownerRatification.canonicalByteManifest.entries.length,7);assert.equal(p.invariants.rawCorrectiveHistoryImmutable,true);});
test('exact certification vocabulary and complete successor denominator are compiled',()=>{const c=JSON.parse(fs.readFileSync('docs/OPS/R24/CORRECTIVE/POST_AUDIT_CURRENT_CERTIFICATION_SET_V2.json'));assert.deepEqual(c.effectiveStateEnum,['CERTIFIED_DONE','DONE_UNCERTIFIED','CERTIFICATION_PENDING','CERTIFICATION_INVALIDATED','INELIGIBLE_OPTIONAL','BLOCKED_TYPED']);assert.equal(c.stages.length,33);assert.equal(c.stages.every(x=>x.effectiveState==='CERTIFIED_DONE'),true);assert.equal(c.artifactBindingDenominator,137);assert.equal(c.verifiedArtifactBindingCount,137);assert.equal(c.externalSourcePlanDigest,'1f5b5b7b63a9f7806db1ecbcd8fa5f16484a73df3fe51f9a5d699d52f4c3fb9a');assert.equal(c.compiledProgramFileDigest,'da754a8a0e2c09014f342b908502e83ab975488ab665feb2a8a66d0b0d46ae0a');});
test('coherent Node npm Electron engine-strict contract is exact',()=>{const result=verifyToolchain();assert.equal(result.node,EXPECTED.node);assert.equal(result.npm,EXPECTED.npm);assert.equal(result.electron,EXPECTED.electron);assert.equal(result.packageManager,'npm@10.9.0');});
test('renderer build policy is local-only and commits the append-only WP503 deterministic runtime successor',()=>{const build=fs.readFileSync('scripts/build-renderer.mjs','utf8');assert.equal(build.includes('LOCAL_NODE_MODULES_REQUIRED'),true);assert.equal(build.includes('preferredSiblingRoots'),false);assert.equal(build.includes("target: ['node22']"),true);const contract=JSON.parse(fs.readFileSync('docs/OPS/R24/CORRECTIVE/POST_AUDIT_CORRECTIONS_CONTRACT_V1.json'));const successor=JSON.parse(fs.readFileSync('docs/OPS/R24/CORRECTIVE/POST_AUDIT_TOOLCHAIN_BUNDLE_SUCCESSOR_V1.json'));assert.equal(contract.rendererBuild.buildToCleanTreeRequired,true);assert.equal(contract.rendererBuild.editorBundleSha256,'664aa13475592f97d7300ef417794815e5edcc0eee0451b3c1859d7cea41a0b4');assert.equal(successor.historicalContract.editorBundleSha256,contract.rendererBuild.editorBundleSha256);assert.equal(successor.historicalContract.sha256,sha256(fs.readFileSync('docs/OPS/R24/CORRECTIVE/POST_AUDIT_CORRECTIONS_CONTRACT_V1.json')));assert.equal(successor.successor.evaluationBaseSha,EXPECTED.bundleBuildBaseSha);assert.equal(successor.successor.evaluationBaseTreeSha,EXPECTED.bundleBuildBaseTreeSha);assert.equal(successor.successor.editorBundleSha256,EXPECTED.editorBundleSha256);assert.equal(successor.successor.editorBundleSha256,sha256(gitObjectBytes(EXPECTED.bundleArtifactSha,'src/renderer/editor.bundle.js')));assert.notEqual(successor.successor.editorBundleSha256,sha256(fs.readFileSync('src/renderer/editor.bundle.js')));assert.equal(successor.programDone,false);});
test('literal inventory script exists and invokes canonical checker after exact-toolchain precheck',()=>{const p=JSON.parse(fs.readFileSync('package.json'));assert.equal(p.packageManager,'npm@10.9.0');assert.equal(p.scripts['r24:test-inventory'],'npm run -s r24:toolchain && node scripts/ops/r24/test-inventory.mjs --check docs/OPS/R24/CORRECTIVE/C1B_TEST_INVENTORY_V1.json');});
test('merge-gate topology requires the complete declared dependency set',()=>{const workflow=fs.readFileSync('.github/workflows/oss-policy.yml','utf8');const result=verifyWorkflowText(workflow);assert.deepEqual(result.dependencies,[...REQUIRED_DEPENDENCIES]);for(const token of ['actual-renderer-build-rtk:','privacy-negative:','static-security-sast:','live-ruleset-oracle:','merge-gate:','if: ${{ always() }}'])assert.equal(workflow.includes(token),true,token);});
test('merge-gate accepts only exact all-success results',()=>{const success=Object.fromEntries(REQUIRED_DEPENDENCIES.map(k=>[k,'success']));assert.equal(verifyDependencyResults(success).status,'PASS');for(const state of ['failure','cancelled','skipped']){const mutant={...success,[REQUIRED_DEPENDENCIES[0]]:state};assert.throws(()=>verifyDependencyResults(mutant),/E_DEPENDENCY_NOT_SUCCESS/);}assert.throws(()=>verifyDependencyResults({...success,unexpected:'success'}),/E_DEPENDENCY_SET/);});
test('live ruleset oracle accepts only the exact retained protection set with sole merge-gate context',()=>{const good=rulesetEnvelope(),ownerView=rulesetEnvelope({currentUserCanBypass:'never'});assert.equal(verifyRuleset(good).status,'PASS');assert.equal(verifyRuleset(ownerView).status,'PASS');const wrong=structuredClone(good);wrong.rules.at(-1).parameters.required_status_checks[0].context='oss-policy';assert.throws(()=>verifyRuleset(wrong),/E_RULESET_STATUS_CHECK_POLICY|E_RULESET_REQUIRED_CONTEXTS/);assert.throws(()=>verifyRuleset({...good,bypass_actors:[{}]}),/E_RULESET_BYPASS/);const noConversation=structuredClone(good);noConversation.rules[2].parameters.required_review_thread_resolution=false;assert.throws(()=>verifyRuleset(noConversation),/E_RULESET_PULL_REQUEST_PROTECTION/);});
test('live ruleset oracle rejects every duplicate intended rule type before map construction',()=>{const good=rulesetEnvelope();for(const type of ['deletion','non_fast_forward','pull_request','required_status_checks']){const mutant=structuredClone(good),index=mutant.rules.findIndex((rule)=>rule.type===type);mutant.rules[(index+1)%mutant.rules.length]=structuredClone(mutant.rules[index]);assert.throws(()=>verifyRuleset(mutant),/E_RULESET_DUPLICATE_OR_MISSING_RULE_TYPE/);}});
test('live ruleset oracle rejects missing bypass semantics bypass-capable user and envelope substitution',()=>{const missing=rulesetEnvelope();delete missing.bypass_actors;assert.throws(()=>verifyRuleset(missing),/E_RULESET_ENVELOPE|E_RULESET_BYPASS/);assert.throws(()=>verifyRuleset(rulesetEnvelope({currentUserCanBypass:'always'})),/E_RULESET_CURRENT_USER_BYPASS/);const unknown=rulesetEnvelope();unknown.role='admin';assert.throws(()=>verifyRuleset(unknown),/E_RULESET_ENVELOPE/);});
test('restricted live observer can prove omitted bypass actors only by exact equality with pinned full authority bytes',()=>{const observer=rulesetEnvelope({currentUserCanBypass:'never'});delete observer.bypass_actors;observer.created_at=new Date(observer.created_at).toISOString();observer.updated_at=new Date(observer.updated_at).toISOString();const result=verifyRulesetObserverWithAuthority({observerRuleset:observer});assert.equal(result.status,'PASS');assert.equal(result.protections.bypassActorCount,0);assert.equal(result.proofMode,'LIVE_RESTRICTED_OBSERVER_EXACTLY_MATCHES_PINNED_FULL_AUTHORITY_BYTES');const drift=structuredClone(observer);drift.updated_at='2026-08-31T01:53:58.000Z';assert.throws(()=>verifyRulesetObserverWithAuthority({observerRuleset:drift}),/E_RULESET_OBSERVER_AUTHORITY_DRIFT/);const unknown={...observer,role:'observer'};assert.throws(()=>verifyRulesetObserverWithAuthority({observerRuleset:unknown}),/E_RULESET_OBSERVER_ENVELOPE/);});
test('live ruleset oracle rejects unknown and missing rule types',()=>{const unknown=rulesetEnvelope();unknown.rules[0]={type:'creation'};assert.throws(()=>verifyRuleset(unknown),/E_RULESET_UNKNOWN_RULE_TYPE/);const missing=rulesetEnvelope();missing.rules.pop();assert.throws(()=>verifyRuleset(missing),/E_RULESET_RULE_COUNT/);});
test('required CI covers three platforms real build RTK SAST and privacy negative',()=>{const c1a=fs.readFileSync('.github/workflows/r24-c1a-hermetic.yml','utf8'),parity=fs.readFileSync('.github/workflows/x1-runtime-parity.yml','utf8'),root=fs.readFileSync('.github/workflows/oss-policy.yml','utf8');for(const os of ['ubuntu-latest','macos-latest','windows-latest']){assert.equal(c1a.includes(os),true);assert.equal(parity.includes(os),true);}for(const token of ['npm ci --engine-strict','npm run build:renderer','git diff --exit-code -- src/renderer/editor.bundle.js src/preload.bundle.cjs','npm run test:rtk','semgrep==1.175.0','b3c08-support-bundle-privacy.contract.test.js'])assert.equal((c1a+'\n'+root).includes(token),true,token);});
test('Windows c1a launches npm through an executable and fails closed on invalid launch authority',()=>{const source=fs.readFileSync('scripts/run-tests.js','utf8');for(const token of ["process.env.npm_execpath","command = process.execPath","path.isAbsolute(npmExecPath)","E_NPM_EXEC_PATH_INVALID=1","process.env.ComSpec","E_WINDOWS_COMMAND_SHELL_INVALID=1","E_PERF_BASELINE_SPAWN="])assert.equal(source.includes(token),true,token);assert.equal(source.includes("process.platform === 'win32' ? 'npm.cmd' : 'npm'"),false);});
test('direct closure authority and durable carrier policy are mandatory',()=>{const trust=JSON.parse(fs.readFileSync('docs/OPS/R24/CORRECTIVE/POST_AUDIT_TERMINAL_TRUST_MODEL_V1.json'));assert.equal(trust.verification.downloadedRemoteArchiveRequired,true);assert.equal(trust.verification.localSelfIssuedReceiptAccepted,false);assert.equal(trust.predecessors.wp400Closure.stageInstanceDigest,'8102a6a2b36a033ef96921774a4c98f1f48f99a876d6e9dc843d416acfdbbcc6');assert.equal(trust.predecessors.wp400Closure.effectiveStateDigest,'1e23d7eae55b658a68f93893c11d01069c3f04427c0a6ece9214bb6e3e2bff0d');assert.equal(trust.retention.durableCanonicalCarrierRequired,true);});
test('whole static correction contract passes and verifies a durable carrier whenever present',()=>{const result=verifyPostAuditCorrections();assert.equal(result.status,'PASS');assert.equal(result.stageCount,33);assert.equal(Boolean(result.durableCarrier),fs.existsSync('docs/OPS/R24/CORRECTIVE/POST_AUDIT_TERMINAL_ATTESTATION_DURABLE_CARRIER_V1.json'));assert.equal(result.programDone,false);});
test('audit-cycle-one successor is independently admitted at lease 57 WIP one',()=>{const result=verifyClosureAdmission();assert.equal(result.status,0,result.stderr);const parsed=JSON.parse(result.stdout);assert.equal(parsed.status,'PASS');assert.equal(parsed.authorityDigest,CLOSURE_AUTHORITY_DIGEST);assert.equal(parsed.stageInstanceDigest,'84bd35e761567556cee248d6c9edeca91b0fc1174b261ffe71fea50193829442');assert.equal(parsed.writeSetDigest,'fb434ff3595c05602d1a53cc82905b1b59e58723fd4b3320eba5315f9ac9bbb0');const admission=JSON.parse(fs.readFileSync(CLOSURE_ADMISSION));assert.equal(admission.externalSourcePlanDigest,'1f5b5b7b63a9f7806db1ecbcd8fa5f16484a73df3fe51f9a5d699d52f4c3fb9a');assert.equal(admission.compiledProgramFileDigest,'da754a8a0e2c09014f342b908502e83ab975488ab665feb2a8a66d0b0d46ae0a');assert.deepEqual(admission.lease,{fencingCounter:57,status:'ACTIVE',wip:1,predecessorReleaseDigest:'003e51ce6fe7b6b888b160c5c310bd3f3bf833903f39dc508809c22580d13191'});});
test('audit-cycle-two V18 one-path successor is independently admitted at lease 58 WIP one',()=>{const result=verifyCycle2Admission();assert.equal(result.status,0,result.stderr);const parsed=JSON.parse(result.stdout),authorityDigest=sha256(fs.readFileSync(CYCLE2_AUTHORITY)),instanceDigest=sha256(fs.readFileSync(CYCLE2_INSTANCE)),admission=readJson(CYCLE2_ADMISSION);assert.equal(parsed.status,'PASS');assert.equal(parsed.authorityDigest,authorityDigest);assert.equal(parsed.stageInstanceDigest,instanceDigest);assert.equal(parsed.stageAdmissionDigest,sha256(fs.readFileSync(CYCLE2_ADMISSION)));assert.equal(parsed.writeSetDigest,'2d45eca2f751fb4f4b6e9abf3a2f369d8597389437875ac7893c3827f6afd260');assert.deepEqual(admission.lease,{fencingCounter:58,status:'ACTIVE',wip:1,predecessorReleaseDigest:'03d722c2476ac80699633890de3bc8aeb89d17a64a22f697c04141815eb7af60'});assert.equal(admission.externalSourcePlanDigest,'1f5b5b7b63a9f7806db1ecbcd8fa5f16484a73df3fe51f9a5d699d52f4c3fb9a');assert.equal(admission.compiledProgramFileDigest,'da754a8a0e2c09014f342b908502e83ab975488ab665feb2a8a66d0b0d46ae0a');});
test('audit-cycle-two terminal workflow binds exact evaluation CI ruleset and one-member artifact',()=>{const workflow=fs.readFileSync('.github/workflows/r24-audit-cycle2-terminal-attestation.yml','utf8');for(const token of ['implementation_candidate_sha:','implementation_merge_sha:','evaluation_sha:','evaluation_tree_sha:','candidate_ci_run_id:','exact_postmerge_ci_run_id:','npm ci --engine-strict','--audit-cycle2-admission','--expected-carrier-digest 596c8fecbc486368e34585505b36b074f1b66ffb5073fc189c086a8e0394db0d','post-audit-merge-gate.mjs --check-live-ruleset','verifyRulesetObserverWithAuthority','durableCarrierValidationSchema:predecessorValidation.schemaVersion','currentUserCanBypassIfPresent:\'never\'','artifactFile:\'audit-cycle2-terminal-attestation.json\'','test "$(find "$RUNNER_TEMP/audit-cycle2-terminal" -type f | wc -l | tr -d \' \')" = 1'])assert.equal(workflow.includes(token),true,token);});
test('closure admission fails closed on coordinated command-scope mutation',()=>{const value=JSON.parse(fs.readFileSync(CLOSURE_INSTANCE));value.commands=[...value.commands,'self-authorized command'];const dir=fs.mkdtempSync(path.join(os.tmpdir(),'post-audit-terminal-closure-mutant-')),file=path.join(dir,'instance.json');fs.writeFileSync(file,`${JSON.stringify(value,null,2)}\n`);const result=verifyClosureAdmission({instance:file});assert.notEqual(result.status,0);assert.match(result.stderr,/E_COMMAND_SCOPE/);});
test('final append-only carriers close every row and release lease 56 at WIP zero',()=>{const result=verifyFinalTransition();assert.equal(result.status,'PASS');assert.equal(result.receiptDigest,'9d9baa275ccebfe73c78810f80366b5eb7bfb466f055b6db8f8516ff4886c144');assert.equal(sha256(fs.readFileSync('docs/OPS/R24/CORRECTIVE/POST_AUDIT_CORRECTIONS_TERMINAL_RECEIPT_V1.json')),'4a6be94c500a36f732f6a9d82f82bd1eff5813e4ffb511d67e0776ad3f4f8379');});
test('final transition rejects a pending row active lease nonzero WIP or PROGRAM_DONE claim',()=>{const matrix=readJson(FINAL_MATRIX);matrix.rows[0].status='CI_PENDING';assert.throws(()=>verifyFinalTransition({matrix}),/true/);const lease=readJson(FINAL_LEASE);lease.lease.status='ACTIVE';lease.lease.wip=1;assert.throws(()=>verifyFinalTransition({lease}));const receipt=readJson(FINAL_RECEIPT);receipt.programDone=true;assert.throws(()=>verifyFinalTransition({receipt}),/false/);});
