'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const model = require('../../src/core/word-manuscript-notes-v1.cjs');
const { buildStoredZip, buildDocxMinBuffer } = require('../../src/export/docx/docxMinBuilder.js');
const { buildCanonicalNotesExport, notePackageParts } = require('../../src/export/docx/docxReviewPacketNotes.js');
const p = text => ({ type: 'paragraph', content: text ? [{ type: 'text', text }] : [] });
const cell = (...content) => ({ type: 'tableCell', attrs: { colspan: 1, rowspan: 1, colwidth: null }, content });
const row = (...content) => ({ type: 'tableRow', content });
const table = (...content) => ({ type: 'table', content });
const doc = (...content) => ({ type: 'doc', content });
const body = () => doc(p('Before'), table(row(cell(p('A')), cell(p(''))), row(cell(p('A')), cell({ type: 'orderedList', attrs: { start: 3 }, content: [{ type: 'listItem', content: [p('List')] }] }))), p('After'));
const W = 'http://schemas.openxmlformats.org/wordprocessingml/2006/main';
const R = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships';
const P = 'http://schemas.openxmlformats.org/package/2006/relationships';
// Literal external package, independently authored: not generated by the table exporter.
function literal(kind = 'footnote', tableXml, styles) {
  const t = tableXml ?? '<w:tbl><w:tblPr><w:tblW w:w="0" w:type="auto"/></w:tblPr><w:tblGrid><w:gridCol w:w="1440"/><w:gridCol w:w="1440"/></w:tblGrid><w:tr><w:tc><w:tcPr><w:vMerge w:val="restart"/></w:tcPr><w:p><w:r><w:t>A</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>B</w:t></w:r></w:p></w:tc></w:tr><w:tr><w:tc><w:tcPr><w:vMerge/></w:tcPr><w:p/></w:tc><w:tc><w:p><w:r><w:t>C</w:t></w:r></w:p></w:tc></w:tr></w:tbl>';
  return buildStoredZip([
    ...(styles ? [{ name: 'word/styles.xml', data: `<w:styles xmlns:w="${W}">${styles}</w:styles>` }] : []),
    { name: '[Content_Types].xml', data: `<Types xmlns="${P.replace('relationships', 'content-types')}"><Default Extension="xml" ContentType="application/xml"/><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/${kind}s.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.${kind}s+xml"/></Types>` },
    { name: '_rels/.rels', data: `<Relationships xmlns="${P}"><Relationship Id="d" Type="${R}/officeDocument" Target="word/document.xml"/></Relationships>` },
    { name: 'word/_rels/document.xml.rels', data: `<Relationships xmlns="${P}"><Relationship Id="n" Type="${R}/${kind}s" Target="${kind}s.xml"/></Relationships>` },
    { name: 'word/document.xml', data: `<w:document xmlns:w="${W}"><w:body><w:p><w:r><w:t>Text</w:t><w:${kind}Reference w:id="1"/></w:r></w:p></w:body></w:document>` },
    { name: `word/${kind}s.xml`, data: `<w:${kind}s xmlns:w="${W}"><w:${kind} w:id="1"><w:p><w:r><w:${kind}Ref/><w:t>Before</w:t></w:r></w:p>${t}<w:p><w:r><w:t>After</w:t></w:r></w:p></w:${kind}></w:${kind}s>` },
  ]);
}
test('Core note tables retain explicit cell ownership, empty/repeated text and independent lists', () => {
  const parsed = model.validateNoteBody(body());
  assert.equal(parsed.text, 'Before\nA\n\nA\nList\nAfter');
  assert.deepEqual(parsed.body, body());
  assert.deepEqual(parsed.paragraphs.map(x => x.table ? [x.table.row, x.table.column] : null), [null, [0, 0], [0, 1], [1, 0], [1, 1], null]);
  assert.equal(parsed.paragraphs[4].list.start, 3);
});
test('literal native footnote and endnote tables preserve vertical merges without synthetic paragraphs', async () => {
  const bridge = await import('../../src/io/revisionBridge/index.mjs');
  for (const kind of ['footnote', 'endnote']) {
    const preview = bridge.buildDocxContentPreviewFromZipBytes(literal(kind));
    assert.equal(preview.ok, true, JSON.stringify(preview));
    const note = preview.contentPreview.manuscriptNotes[0];
    assert.equal(note.kind, kind);
    assert.equal(model.validateNoteBody(note.body).text, 'Before\nA\nB\nC\nAfter');
    assert.equal(note.body.content[1].type, 'table');
    assert.equal(note.body.content[1].content[0].content[0].attrs.rowspan, 2);
    assert.equal(note.body.content[1].content[1].content.length, 1);
  }
});
test('note table export roundtrip retains topology and cell lists in both note kinds', async () => {
  const bridge = await import('../../src/io/revisionBridge/index.mjs');
  const block = { sceneId: 'roman/a.txt', blockId: 'b', documentParagraphIndex: 0, text: 'Text', formatIr: { runs: [{ text: 'Text' }] } };
  const value = body();
  const document = { schemaVersion: 1, projectId: 'p', notes: ['footnote', 'endnote'].map(kind => ({ id: kind, scope: 'manuscript', title: '', body: model.validateNoteBody(value).text,
    manuscript: model.bindManuscriptPayload({ body: value, kind, sceneId: block.sceneId, offsetUtf16: 2, sceneContent: block.text }) })) };
  const projection = buildCanonicalNotesExport(document, [], [block], 'p', { editableReturn: true });
  const parts = notePackageParts(projection);
  for (const part of parts.entries.filter(x => /notes.xml$/.test(x.name))) {
    assert.equal((part.data.match(/<w:tbl>/g) || []).length, 1);
    assert.equal((part.data.match(/<w:tc>/g) || []).length, 4);
  }
  const [docxPageSetupBindModule, semanticMappingModule, styleMapModule] = await Promise.all([
    import('../../src/docxPageSetupBind.mjs'), import('../../src/derived/semanticMapping.mjs'), import('../../src/derived/styleMap.mjs'),
  ]);
  const bytes = buildDocxMinBuffer({ doc: doc(p('Text')), plainText: 'Text', bookProfile: { formatId: 'A4' } },
    { docxPageSetupBindModule, semanticMappingModule, styleMapModule, documentNotes: projection, noteBlocks: [block] });
  const result = bridge.buildDocxContentPreviewFromZipBytes(bytes);
  assert.equal(result.ok, true, JSON.stringify(result));
  assert.deepEqual(result.contentPreview.manuscriptNotes.map(n => n.body), [value, value]);
});
test('Core refuses ragged, nested, unknown and over-budget note tables', () => {
  for (const value of [doc(table(row(cell(p('a')), cell(p('b'))), row(cell(p('c'))))),
    doc(table(row(cell(table(row(cell(p('nested')))))))),
    doc(table(row({ ...cell(p('a')), authority: 'write' }))),
    doc(table(row(cell({ type: 'heading', content: [{ type: 'text', text: 'heading' }] })))),
    doc(table(...Array.from({ length: 129 }, () => row(cell(p('x'))))))]) {
    assert.throws(() => model.validateNoteBody(value), /NOTE_BODY_/);
  }
});
test('actual note editor table schema preserves cell editing without enabling headings', async () => {
  const { getSchema } = await import('@tiptap/core');
  const { default: StarterKit } = await import('@tiptap/starter-kit');
  const { DocumentTables } = await import('../../src/renderer/tiptap/documentTables.mjs');
  const schema = getSchema([StarterKit.configure({ heading: false, codeBlock: false }),
    DocumentTables.configure({ cellContent: '(paragraph | bulletList | orderedList)+' })]);
  const roundtrip = schema.nodeFromJSON(body());
  roundtrip.check();
  assert.equal(model.validateNoteBody(roundtrip.toJSON()).text, 'Before\nA\n\nA\nList\nAfter');
  assert.equal(schema.nodes.heading, undefined);
});

const styledTable = (direct = '') => `<w:tbl><w:tblPr><w:tblStyle w:val="grid"/>${direct}</w:tblPr><w:tblGrid><w:gridCol w:w="2000"/></w:tblGrid><w:tr><w:tc><w:p><w:r><w:t>Styled</w:t></w:r></w:p></w:tc></w:tr></w:tbl>`;
const allEdges = ['top', 'left', 'bottom', 'right', 'insideH', 'insideV'].map(edge => `<w:${edge} w:val="single" w:sz="4" w:color="auto"/>`).join('');
const baseStyle = `<w:style w:type="table" w:styleId="base"><w:tblPr><w:tblBorders>${allEdges}</w:tblBorders><w:shd w:val="clear" w:fill="ABCDEF"/></w:tblPr></w:style>`;
const derivedStyle = extra => `<w:style w:type="table" w:styleId="grid"><w:basedOn w:val="base"/>${extra}</w:style>`;
test('note table styles materialize inherited borders/fill and respect literal overrides', async () => {
  const bridge = await import('../../src/io/revisionBridge/index.mjs');
  for (const kind of ['footnote', 'endnote']) {
    const parsed = bridge.buildDocxContentPreviewFromZipBytes(literal(kind, styledTable('<w:tblBorders><w:top w:val="double" w:sz="8" w:color="FF0000"/></w:tblBorders><w:shd w:val="clear" w:fill="auto"/>'), baseStyle + derivedStyle('<w:tblPr><w:tblBorders><w:bottom w:val="nil"/></w:tblBorders></w:tblPr>')));
    assert.equal(parsed.ok, true, JSON.stringify(parsed));
    const props = parsed.contentPreview.manuscriptNotes[0].body.content[1].attrs.wordTable;
    assert.deepEqual(props.borders.top, { style: 'double', size: 8, color: 'FF0000' });
    assert.deepEqual(props.borders.bottom, { style: 'nil' });
    assert.deepEqual(props.borders.left, { style: 'single', size: 4, color: 'auto' });
    assert.equal(props.shading, 'none');
    assert.deepEqual(props.grid, [2000]);
  }
  const legacy = bridge.buildDocxContentPreviewFromZipBytes(literal('footnote', styledTable(), `<w:style w:type="table" w:styleId="grid"><w:tblPr><w:tblBorders>${allEdges}</w:tblBorders></w:tblPr></w:style>`));
  assert.equal(legacy.ok, true, JSON.stringify(legacy));
  assert.equal(Object.keys(legacy.contentPreview.manuscriptNotes[0].body.content[1].attrs.wordTable.borders).length, 6);
});
test('note table style loss, cycles, unknown effects and non-neutral geometry block import', async () => {
  const bridge = await import('../../src/io/revisionBridge/index.mjs');
  const variants = [derivedStyle(''), baseStyle + derivedStyle('<w:tblStylePr w:type="firstRow"><w:rPr><w:b/></w:rPr></w:tblStylePr>'),
    baseStyle + derivedStyle('<w:rPr><w:b/></w:rPr>'), baseStyle + derivedStyle('<w:pPr><w:spacing w:after="100"/></w:pPr>'),
    baseStyle + derivedStyle('<w:pPr><w:spacing w:after="0" w:afterAutospacing="1"/></w:pPr>'),
    baseStyle + derivedStyle('<w:tblPr><w:tblCellMar><w:left w:w="999" w:type="dxa"/></w:tblCellMar></w:tblPr>'),
    '<w:style w:type="table" w:styleId="grid"><w:basedOn w:val="grid"/></w:style>',
    baseStyle + derivedStyle('<w:basedOn w:val="base"/>')];
  for (const styles of variants) {
    const parsed = bridge.buildDocxContentPreviewFromZipBytes(literal('endnote', styledTable(), styles));
    assert.equal(parsed.ok, false, JSON.stringify(parsed));
  }
});

test('note history routing binds the current editor and never falls through on empty or disabled history', async () => {
  const fs = require('node:fs');
  const source = fs.readFileSync(require.resolve('../../src/renderer/tiptap/runtimeBridge.js'), 'utf8');
  const { createTiptapRuntimeBridge } = await import(`data:text/javascript,${encodeURIComponent(source)}`);
  const calls = [];
  const scene = { commands: { undo: () => { calls.push('scene-undo'); return true; }, redo: () => { calls.push('scene-redo'); return true; } } };
  const note = { commands: { undo: () => { calls.push('note-undo'); return false; }, redo: () => { calls.push('note-redo'); return true; } } };
  let focused = note;
  const bridge = createTiptapRuntimeBridge({ editor: scene, resolveHistoryEditor: () => focused });
  assert.equal(bridge.handleRuntimeCommand({ commandId: 'cmd.project.edit.undo' }).result.performed, false);
  assert.equal(bridge.handleRuntimeCommand({ command: 'edit-redo' }).result.performed, true);
  note.isEditable = false;
  assert.equal(bridge.undo().performed, false);
  note.isEditable = true; note.isDestroyed = true;
  assert.equal(bridge.redo().performed, false);
  focused = null;
  assert.equal(bridge.undo().performed, false);
  focused = scene;
  assert.equal(bridge.undo().performed, true);
  assert.deepEqual(calls, ['note-undo', 'note-redo', 'scene-undo']);
});

test('paste target is revalidated after returning from Word without changing DOM focus', () => {
  const fs = require('node:fs'), vm = require('node:vm');
  const source = fs.readFileSync(require.resolve('../../src/renderer/editor.js'), 'utf8');
  const fragment = source.slice(source.indexOf('function isEditorPasteTargetFocused()'), source.indexOf("const statusElement = document.getElementById('status');"));
  const handlers = {}, calls = [];
  class Element { closest() { return this; } contains(value) { return value === this; } }
  const editable = new Element(); editable.isContentEditable = true;
  const document = { activeElement: editable, addEventListener() {} };
  const window = { addEventListener: (type, fn) => { handlers[type] = fn; }, requestAnimationFrame: fn => fn(), electronAPI: { notifyEditorPasteFocusState: state => calls.push(state) } };
  vm.runInNewContext(fragment, { window, document, HTMLElement: Element });
  handlers.blur(); handlers.focus();
  assert.deepEqual(calls, [true, false, true]);
  editable.isContentEditable = false; handlers.focus();
  assert.equal(calls.at(-1), false);
  document.activeElement = {}; handlers.focus();
  assert.equal(calls.at(-1), false);
});

test('implicit default table style is retained and unsupported defaults are never silently flattened', async () => {
  const bridge = await import('../../src/io/revisionBridge/index.mjs');
  const xml = styledTable().replace('<w:tblStyle w:val="grid"/>', '');
  const style = `<w:style w:type="table" w:default="1" w:styleId="grid"><w:tblPr><w:tblBorders>${allEdges}</w:tblBorders></w:tblPr></w:style>`;
  const value = bridge.buildDocxContentPreviewFromZipBytes(literal('endnote', xml, style));
  assert.equal(value.ok, true, JSON.stringify(value));
  assert.equal(Object.keys(value.contentPreview.manuscriptNotes[0].body.content[1].attrs.wordTable.borders).length, 6);
  const bad = bridge.buildDocxContentPreviewFromZipBytes(literal('endnote', xml, style.replace('</w:style>', '<w:rPr><w:b/></w:rPr></w:style>')));
  assert.equal(bad.ok, false);
});

test('bounded confirmation discloses table ownership, topology and property-only changes before Apply', async () => {
  const fs = require('node:fs'), vm = require('node:vm'), { createRequire } = require('node:module');
  const mainPath = require.resolve('../../src/main.js');
  const source = fs.readFileSync(mainPath, 'utf8');
  const fragment = source.slice(source.indexOf('async function confirmLocalWordNoteDelta('), source.indexOf('async function confirmLocalWordCommentDelta('));
  let shown;
  const parent = { isDestroyed: () => false }, BrowserWindow = function OwnedBrowserWindow() {}, screen = { ownedDisplay: true };
  const ctx = vm.createContext({ require: createRequire(mainPath), manuscriptNoteModel: model, mainWindow: parent, BrowserWindow, screen,
    confirmWordReturn: async (request, adapter) => {
      assert.equal(request.parent, parent); assert.equal(adapter.BrowserWindow, BrowserWindow); assert.equal(adapter.screen, screen);
      shown = request; return false;
    }, dialog: { showMessageBox: () => { throw Error('UNSAFE_NATIVE_NOTE_CONFIRMATION'); } } });
  vm.runInContext(fragment, ctx);
  const before = model.bindManuscriptPayload({ body: body(), kind: 'footnote', sceneId: 'roman/a.txt', offsetUtf16: 0, sceneContent: 'Text' });
  const after = JSON.parse(JSON.stringify(before));
  after.body.content[1].attrs = { wordTable: { ...require('../../src/io/documentTableProperties.js').legacyTableProperties(2), grid: [2000, 3000], shading: 'ABCDEF' } };
  after.body.content[1].content[0].content[0].attrs.wordCell = { version: 1, shading: null, borders: {}, widthDxa: 4675 };
  assert.equal(await ctx.confirmLocalWordNoteDelta({ fileName: 'table.docx', changes: [{ operation: 'update', before, after }] }), false);
  for (const text of ['Таблица 1: 2 строк, 2 столбцов', 'строка 2, столбец 2', '100 пт, 150 пт', '#ABCDEF', 'предпочтительная ширина 233.75 пт', 'одинарная 0.5 пт', 'объединение 1 × 1', 'Оформление до:', 'Оформление после:']) assert(shown.detail.includes(text), text);
  assert.equal(shown.title, 'Сноски из Word'); assert.equal(shown.message, 'Применить изменения сносок?');
  assert.match(shown.detail, /^table\.docx\nИзменений: 1\. Удалённых: 0\./u);
  assert.match(shown.detail, /Удалённые сноски сохранятся с отметкой удаления\.$/u);
});

async function tableReturnFixture(kind, mutate = value => value, explicit = true) {
  const { buildFullManuscriptDocxReviewPacketSource } = require('../../src/export/docx/fullManuscriptDocxReviewPacketSource.js');
  const { buildDocxReviewPacketBuffer } = require('../../src/export/docx/docxReviewPacketBuilder.js');
  const { legacyTableProperties } = require('../../src/io/documentTableProperties.js');
  const bridge = await import('../../src/io/revisionBridge/index.mjs');
  const sceneId = 'roman/a.txt', text = 'Text', projectId = 'table-return';
  const richBody = body();
  if (explicit) richBody.content[1].attrs = { wordTable: { ...legacyTableProperties(2), grid: [2000, 2000] } };
  const document = { schemaVersion: 1, projectId, notes: [{ id: 'table-note', title: '', scope: 'manuscript',
    body: model.validateNoteBody(richBody).text,
    manuscript: model.bindManuscriptPayload({ kind, body: richBody, sceneId, offsetUtf16: 2, sceneContent: text }) },
  { id: 'private', title: 'Private', body: 'Do not export or change', scope: 'project' }] };
  const source = buildFullManuscriptDocxReviewPacketSource({ projectId, projectRoot: '/project', notesDocument: document,
    scenes: [{ sceneId, scenePath: '/project/' + sceneId, order: 0, text, doc: doc(p(text)) }] });
  const original = buildDocxReviewPacketBuffer(source);
  const parts = { ...bridge.extractDocxReviewTransportPackagePartsFromZipBytes({ bytes: original }).parts };
  const part = `word/${kind}s.xml`;
  parts[part] = mutate(parts[part]);
  const bytes = buildStoredZip(Object.entries(parts).map(([name, data]) => ({ name, data })));
  const stable = value => Array.isArray(value) ? `[${value.map(stable).join(',')}]` : value && typeof value === 'object'
    ? `{${Object.keys(value).sort().map(key => `${JSON.stringify(key)}:${stable(value[key])}`).join(',')}}` : JSON.stringify(value);
  const parsed = bridge.buildDocxReviewTransportAnalysisFromZipBytes({ bytes }, { cryptoPort: {
    sha256Text: model.sha, sha256Json: value => 'sha256:' + model.sha(stable(value)), byteLength: value => Buffer.byteLength(value),
  } });
  assert.equal(parsed.ok, true, JSON.stringify(parsed.reasons));
  const returnedNotes = bridge.parseDocumentNotesRichReturn(bytes, parsed.reviewIr.documentNotes, { includeBreakProjection: true });
  assert.equal(model.validateNoteBody(returnedNotes[0].body).text, document.notes[0].body, 'fixture changes no note text');
  return { document, returnedNotes, input: { document, projectId, roundId: 'table-only', artifactSha256: model.sha(bytes),
    baseline: source.documentNotes, exportMap: source.localAuthorityCapsule.exportMap, returnedNotes,
    returnedParagraphs: parsed.reviewIr.formattingParagraphs, now: '2026-10-01T09:00:00Z' } };
}

const tableOnlyChanges = {
  preferredCellWidth: xml => xml.replace('<w:tcW w:w="2000"', '<w:tcW w:w="4675"'),
  grid: xml => xml.replaceAll('w:w="2000"', 'w:w="2500"'),
  width: xml => xml.replace('<w:tblPr>', '<w:tblPr><w:tblW w:w="5000" w:type="dxa"/>'),
  border: xml => xml.replace('<w:top w:val="single" w:sz="4" w:color="auto"/>', '<w:top w:val="double" w:sz="8" w:color="FF0000"/>'),
  fill: xml => xml.replace('<w:tblPr>', '<w:tblPr><w:shd w:val="clear" w:fill="ABCDEF"/>'),
  cellFill: xml => xml.replace('<w:tcPr>', '<w:tcPr><w:shd w:val="clear" w:fill="CDEFAB"/>'),
  cellBorder: xml => xml.replace('<w:tcPr>', '<w:tcPr><w:tcBorders><w:bottom w:val="nil"/></w:tcBorders>'),
  header: xml => xml.replace('<w:tr>', '<w:tr><w:trPr><w:tblHeader/></w:trPr>'),
  rows: xml => xml.replace(/<w:tbl>[\s\S]*?<\/w:tbl>/u, tableXml => {
    const cells = [...tableXml.matchAll(/<w:tc>[\s\S]*?<\/w:tc>/gu)].map(match => match[0]);
    assert.equal(cells.length, 4);
    return '<w:tbl><w:tblGrid><w:gridCol w:w="2000"/></w:tblGrid>' + cells.map(cellXml => `<w:tr>${cellXml}</w:tr>`).join('') + '</w:tbl>';
  }),
  removeTable: xml => xml.replace(/<w:tbl>[\s\S]*?<\/w:tbl>/u, tableXml =>
    [...tableXml.matchAll(/<w:tc>([\s\S]*?)<\/w:tc>/gu)].map(match => match[1].replace(/<w:tcPr>[\s\S]*?<\/w:tcPr>/u, '')).join('')),
};

for (const kind of ['footnote', 'endnote']) {
  test(`${kind} table-only return preserves every changed property and topology with identical text`, async () => {
    const { planNoteReturnDelta } = require('../../src/core/word-note-return-delta-v1.cjs');
    for (const [label, mutate] of Object.entries(tableOnlyChanges)) {
      const fixture = await tableReturnFixture(kind, mutate);
      const result = planNoteReturnDelta(fixture.input);
      assert.equal(result.changes.length, 1, label);
      assert.equal(result.changes[0].operation, 'update', label);
      assert.deepEqual(result.document.notes[0].manuscript.body, fixture.returnedNotes[0].body, label);
      assert.deepEqual(result.document.notes[0].manuscript.reference, fixture.document.notes[0].manuscript.reference, label);
      assert.deepEqual(result.document.notes[1], fixture.document.notes[1], label);
      assert.equal(planNoteReturnDelta({ ...fixture.input, document: result.document }).replay, true, label);
      const stale = structuredClone(fixture.document); stale.notes[1].body += '!';
      assert.throws(() => planNoteReturnDelta({ ...fixture.input, document: stale }), /NOTE_RETURN_BASELINE_CONFLICT/, label);
    }
  });
}

test('table return preserves unchanged rich representation and authenticated legacy auto-fit equivalence', async () => {
  const { planNoteReturnDelta } = require('../../src/core/word-note-return-delta-v1.cjs');
  for (const fixture of [await tableReturnFixture('footnote'), await tableReturnFixture('endnote', undefined, false),
    await tableReturnFixture('footnote', xml => xml.replaceAll('w:gridCol w:w="1440"', 'w:gridCol w:w="2500"'), false)]) {
    const result = planNoteReturnDelta(fixture.input);
    assert.equal(result.unchanged, true);
    assert.deepEqual(result.document, fixture.document);
  }
});
