'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const model = require('../../src/core/word-manuscript-notes-v1.cjs');
const { buildStoredZip, buildDocxMinBuffer } = require('../../src/export/docx/docxMinBuilder.js');
const { buildCanonicalNotesExport, notePackageParts } = require('../../src/export/docx/docxReviewPacketNotes.js');
const p = text => ({ type: 'paragraph', content: text ? [{ type: 'text', text }] : [] });
const cell = (...content) => ({ type: 'tableCell', attrs: { colspan: 1, rowspan: 1, colwidth: null }, content });
const row = (...content) => ({ type: 'tableRow', content });
const table = (...content) => ({ type: 'table', content });
const doc = (...content) => ({ type: 'doc', content });
const body = () => doc(p('Before'), table(row(cell(p('A')), cell(p(''))), row(cell(p('A')), cell({ type: 'orderedList', attrs: { start: 3 }, content: [{ type: 'listItem', content: [p('List')] }] }))), p('After'));
const W = 'http://schemas.openxmlformats.org/wordprocessingml/2006/main';
const R = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships';
const P = 'http://schemas.openxmlformats.org/package/2006/relationships';
// Literal external package, independently authored: not generated by the table exporter.
function literal(kind = 'footnote', tableXml) {
  const t = tableXml ?? '<w:tbl><w:tblPr><w:tblW w:w="0" w:type="auto"/></w:tblPr><w:tblGrid><w:gridCol w:w="1440"/><w:gridCol w:w="1440"/></w:tblGrid><w:tr><w:tc><w:tcPr><w:vMerge w:val="restart"/></w:tcPr><w:p><w:r><w:t>A</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>B</w:t></w:r></w:p></w:tc></w:tr><w:tr><w:tc><w:tcPr><w:vMerge/></w:tcPr><w:p/></w:tc><w:tc><w:p><w:r><w:t>C</w:t></w:r></w:p></w:tc></w:tr></w:tbl>';
  return buildStoredZip([
    { name: '[Content_Types].xml', data: `<Types xmlns="${P.replace('relationships', 'content-types')}"><Default Extension="xml" ContentType="application/xml"/><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/${kind}s.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.${kind}s+xml"/></Types>` },
    { name: '_rels/.rels', data: `<Relationships xmlns="${P}"><Relationship Id="d" Type="${R}/officeDocument" Target="word/document.xml"/></Relationships>` },
    { name: 'word/_rels/document.xml.rels', data: `<Relationships xmlns="${P}"><Relationship Id="n" Type="${R}/${kind}s" Target="${kind}s.xml"/></Relationships>` },
    { name: 'word/document.xml', data: `<w:document xmlns:w="${W}"><w:body><w:p><w:r><w:t>Text</w:t><w:${kind}Reference w:id="1"/></w:r></w:p></w:body></w:document>` },
    { name: `word/${kind}s.xml`, data: `<w:${kind}s xmlns:w="${W}"><w:${kind} w:id="1"><w:p><w:r><w:${kind}Ref/><w:t>Before</w:t></w:r></w:p>${t}<w:p><w:r><w:t>After</w:t></w:r></w:p></w:${kind}></w:${kind}s>` },
  ]);
}
test('Core note tables retain explicit cell ownership, empty/repeated text and independent lists', () => {
  const parsed = model.validateNoteBody(body());
  assert.equal(parsed.text, 'Before\nA\n\nA\nList\nAfter');
  assert.deepEqual(parsed.body, body());
  assert.deepEqual(parsed.paragraphs.map(x => x.table ? [x.table.row, x.table.column] : null), [null, [0, 0], [0, 1], [1, 0], [1, 1], null]);
  assert.equal(parsed.paragraphs[4].list.start, 3);
});
test('literal native footnote and endnote tables preserve vertical merges without synthetic paragraphs', async () => {
  const bridge = await import('../../src/io/revisionBridge/index.mjs');
  for (const kind of ['footnote', 'endnote']) {
    const preview = bridge.buildDocxContentPreviewFromZipBytes(literal(kind));
    assert.equal(preview.ok, true, JSON.stringify(preview));
    const note = preview.contentPreview.manuscriptNotes[0];
    assert.equal(note.kind, kind);
    assert.equal(model.validateNoteBody(note.body).text, 'Before\nA\nB\nC\nAfter');
    assert.equal(note.body.content[1].type, 'table');
    assert.equal(note.body.content[1].content[0].content[0].attrs.rowspan, 2);
    assert.equal(note.body.content[1].content[1].content.length, 1);
  }
});
test('note table export roundtrip retains topology and cell lists in both note kinds', async () => {
  const bridge = await import('../../src/io/revisionBridge/index.mjs');
  const block = { sceneId: 'roman/a.txt', blockId: 'b', documentParagraphIndex: 0, text: 'Text', formatIr: { runs: [{ text: 'Text' }] } };
  const value = body();
  const document = { schemaVersion: 1, projectId: 'p', notes: ['footnote', 'endnote'].map(kind => ({ id: kind, scope: 'manuscript', title: '', body: model.validateNoteBody(value).text,
    manuscript: model.bindManuscriptPayload({ body: value, kind, sceneId: block.sceneId, offsetUtf16: 2, sceneContent: block.text }) })) };
  const projection = buildCanonicalNotesExport(document, [], [block], 'p', { editableReturn: true });
  const parts = notePackageParts(projection);
  for (const part of parts.entries.filter(x => /notes.xml$/.test(x.name))) {
    assert.equal((part.data.match(/<w:tbl>/g) || []).length, 1);
    assert.equal((part.data.match(/<w:tc>/g) || []).length, 4);
  }
  const [docxPageSetupBindModule, semanticMappingModule, styleMapModule] = await Promise.all([
    import('../../src/docxPageSetupBind.mjs'), import('../../src/derived/semanticMapping.mjs'), import('../../src/derived/styleMap.mjs'),
  ]);
  const bytes = buildDocxMinBuffer({ doc: doc(p('Text')), plainText: 'Text', bookProfile: { formatId: 'A4' } },
    { docxPageSetupBindModule, semanticMappingModule, styleMapModule, documentNotes: projection, noteBlocks: [block] });
  const result = bridge.buildDocxContentPreviewFromZipBytes(bytes);
  assert.equal(result.ok, true, JSON.stringify(result));
  assert.deepEqual(result.contentPreview.manuscriptNotes.map(n => n.body), [value, value]);
});
test('Core refuses ragged, nested, unknown and over-budget note tables', () => {
  for (const value of [doc(table(row(cell(p('a')), cell(p('b'))), row(cell(p('c'))))),
    doc(table(row(cell(table(row(cell(p('nested')))))))),
    doc(table(row({ ...cell(p('a')), authority: 'write' }))),
    doc(table(row(cell({ type: 'heading', content: [{ type: 'text', text: 'heading' }] })))),
    doc(table(...Array.from({ length: 129 }, () => row(cell(p('x'))))))]) {
    assert.throws(() => model.validateNoteBody(value), /NOTE_BODY_/);
  }
});
test('actual note editor table schema preserves cell editing without enabling headings', async () => {
  const { getSchema } = await import('@tiptap/core');
  const { default: StarterKit } = await import('@tiptap/starter-kit');
  const { DocumentTables } = await import('../../src/renderer/tiptap/documentTables.mjs');
  const schema = getSchema([StarterKit.configure({ heading: false, codeBlock: false }),
    DocumentTables.configure({ cellContent: '(paragraph | bulletList | orderedList)+' })]);
  const roundtrip = schema.nodeFromJSON(body());
  roundtrip.check();
  assert.equal(model.validateNoteBody(roundtrip.toJSON()).text, 'Before\nA\n\nA\nList\nAfter');
  assert.equal(schema.nodes.heading, undefined);
});
